version: 1.0.{build}

os: Visual Studio 2015

platform:
  - x86

branches:
  only:
    - master

install:
 - ps: (new-object net.webclient).DownloadFile('https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi', 'python-3.4.4.msi')
 - ps: msiexec /i python-3.4.4.msi /quiet /qn /norestart
 - cmd: copy c:\python34\python.exe c:\python34\python3.exe
 - ps: (new-object net.webclient).DownloadFile('https://dl.dropboxusercontent.com/u/37517477/ninja.exe', 'ninja.exe')
 - cmd: copy ninja.exe c:\python34

build_script:
  - cmd: echo No build step.

test_script:
  - cmd: c:\python34\python3 run_tests.py --backend=ninja

artifacts:
  - path: meson-test-run.txt
