sudo: required

language: c

services:
  - docker

before_install:
  - docker pull jpakkane/mesonci:xenial

script:
  - docker run jpakkane/mesonci:xenial /bin/sh -c "cd /root && git clone https://github.com/mesonbuild/meson.git && cd meson && ./run_tests.py"
